In [3]:
import pandas as pd 
import numpy as np

## install xlrd to import xls type files

In [4]:
%pip install xlrd

Requirement already satisfied: xlrd in c:\users\arshi\appdata\local\programs\python\python313\lib\site-packages (2.0.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: C:\Users\arshi\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

## to see what files we have in our folder

In [5]:
import os

folder = r"C:\Users\arshi\OneDrive\Desktop\New Project"
print(os.listdir(folder))

['.ipynb_checkpoints', 'Sample_Superstore.ipynb', 'sample_superstore.xls']

In [6]:
import pandas as pd

file_path = r"C:\Users\arshi\OneDrive\Desktop\New Project\sample_superstore.xls"

Orders = pd.read_excel(file_path, sheet_name="Orders")
People = pd.read_excel(file_path, sheet_name="People")
Returns = pd.read_excel(file_path, sheet_name="Returns")

In [7]:
Orders.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870

In [8]:
Orders.sample(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
4427,4428,US-2025-127138,2025-03-12,2025-03-15,Second Class,DK-13225,Dean Katz,Corporate,United States,San Francisco,...,94109,West,OFF-EN-10004459,Office Supplies,Envelopes,Security-Tint Envelopes,30.560,4,0.0,14.9744
5355,5356,US-2025-151092,2025-08-06,2025-08-13,Standard Class,VG-21790,Vivek Gonzalez,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10001700,Technology,Phones,Panasonic KX-TG6844B Expandable Digital Cordle...,211.168,4,0.2,18.4772
9905,9906,US-2026-139199,2026-12-09,2026-12-13,Standard Class,DK-12835,Damala Kotsonis,Corporate,United States,Detroit,...,48234,Central,OFF-PA-10001293,Office Supplies,Paper,Xerox 1946,12.960,2,0.0,6.2208
3616,3617,US-2024-126466,2024-11-09,2024-11-13,Standard Class,JO-15550,Jesus Ocampo,Home Office,United States,Roseville,...,95661,West,OFF-FA-10000490,Office Supplies,Fasteners,"OIC Binder Clips, Mini, 1/4"" Capacity, Black",2.480,2,0.0,1.1656
7026,7027,US-2026-163265,2026-02-16,2026-02-21,Standard Class,JS-16030,Joy Smith,Consumer,United States,Decatur,...,62521,Central,OFF-FA-10004854,Office Supplies,Fasteners,Vinyl Coated Wire Paper Clips in Organizer Box...,18.368,2,0.2,6.1992
5602,5603,US-2025-158778,2025-09-05,2025-09-09,Standard Class,DB-13210,Dean Braden,Consumer,United States,Philadelphia,...,19134,East,OFF-AR-10000896,Office Supplies,Art,Newell 329,7.872,3,0.2,0.5904
8048,8049,US-2026-126179,2026-07-03,2026-07-07,Standard Class,CS-12460,Chuck Sachs,Consumer,United States,Columbus,...,31907,South,TEC-PH-10001557,Technology,Phones,Pyle PMP37LED,287.970,3,0.0,77.7519
5257,5258,US-2025-163776,2025-07-19,2025-07-25,Standard Class,JS-16030,Joy Smith,Consumer,United States,Hattiesburg,...,39401,South,OFF-PA-10001033,Office Supplies,Paper,Xerox 1893,245.940,6,0.0,120.5106
9007,9008,CA-2026-131807,2026-10-05,2026-10-10,Standard Class,GG-14650,Greg Guthrie,Corporate,Canada,Edmonton,...,T5A,West,FUR-FU-10004666,Furniture,Furnishings,DAX Clear Channel Poster Frame,39.920,5,0.2,13.4730
344,345,US-2023-100363,2023-04-08,2023-04-15,Standard Class,JM-15655,Jim Mitchum,Corporate,United States,Glendale,...,85301,West,OFF-FA-10000611,Office Supplies,Fasteners,Binder Clips by OIC,2.368,2,0.2,0.8288

In [9]:
Orders.info

<bound method DataFrame.info of        Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0           1  US-2023-103800 2023-01-03 2023-01-07  Standard Class
1           2  US-2023-112326 2023-01-04 2023-01-08  Standard Class
2           3  US-2023-112326 2023-01-04 2023-01-08  Standard Class
3           4  US-2023-112326 2023-01-04 2023-01-08  Standard Class
4           5  US-2023-141817 2023-01-05 2023-01-12  Standard Class
...       ...             ...        ...        ...             ...
10189   10190  US-2026-143259 2026-12-30 2027-01-03  Standard Class
10190   10191  US-2026-115427 2026-12-30 2027-01-03  Standard Class
10191   10192  US-2026-156720 2026-12-30 2027-01-03  Standard Class
10192   10193  US-2026-143259 2026-12-30 2027-01-03  Standard Class
10193   10194  CA-2026-143500 2026-12-30 2027-01-03  Standard Class

      Customer ID      Customer Name      Segment Country/Region  \
0        DP-13000      Darren Powers     Consumer  United States
1        PO-19195      Phillina Ober  Home Office  United States
2        PO-19195      Phillina Ober  Home Office  United States
3        PO-19195      Phillina Ober  Home Office  United States
4        MB-18085         Mick Brown     Consumer  United States
...           ...                ...          ...            ...
10189    PO-18865  Patrick O'Donnell     Consumer  United States
10190    EB-13975         Erica Bern    Corporate  United States
10191    JM-15580      Jill Matthias     Consumer  United States
10192    PO-18865  Patrick O'Donnell     Consumer  United States
10193    HO-15230        Harry Olson     Consumer         Canada

                City  ... Postal Code   Region       Product ID  \
0            Houston  ...       77095  Central  OFF-PA-10000174
1         Naperville  ...       60540  Central  OFF-BI-10004094
2         Naperville  ...       60540  Central  OFF-LA-10003223
3         Naperville  ...       60540  Central  OFF-ST-10002743
4       Philadelphia  ...       19143     East  OFF-AR-10003478
...              ...  ...         ...      ...              ...
10189  New York City  ...       10009     East  OFF-BI-10003684
10190      Fairfield  ...       94533     West  OFF-BI-10004632
10191       Loveland  ...       80538     West  OFF-FA-10003472
10192  New York City  ...       10009     East  TEC-PH-10004774
10193  Charlottetown  ...         C0A     East  OFF-BI-10004040

              Category Sub-Category  \
0      Office Supplies        Paper
1      Office Supplies      Binders
2      Office Supplies       Labels
3      Office Supplies      Storage
4      Office Supplies          Art
...                ...          ...
10189  Office Supplies      Binders
10190  Office Supplies      Binders
10191  Office Supplies    Fasteners
10192       Technology       Phones
10193  Office Supplies      Binders

                                            Product Name    Sales  Quantity  \
0      Message Book, Wirebound, Four 5 1/2" X 4" Form...   16.448         2
1             GBC Standard Plastic Binding Systems Combs    3.540         2
2                                              Avery 508   11.784         3
3                          SAFCO Boltless Steel Shelving  272.736         3
4      Avery Hi-Liter EverBold Pen Style Fluorescent ...   19.536         3
...                                                  ...      ...       ...
10189               Wilson Jones Legal Size Ring Binders   52.776         3
10190                                 GBC Binding covers   20.720         2
10191                                Bagged Rubber Bands    3.024         3
10192                          Gear Head AU3700S Headset   90.930         7
10193                        Wilson Jones Impact Binders    3.024         3

       Discount   Profit
0           0.2   5.5512
1           0.8  -5.4870
2           0.2   4.2717
3           0.2 -64.7748
4           0.2   4.8840
...         ...      ...
10189       0.2  19.7910
10190       0.2   6.4750
10191       0.2  -0.6048
10192       0.0   2.7279
10193       0.2  -0.6048

[10194 rows x 21 columns]>

In [10]:
Orders.describe

<bound method NDFrame.describe of        Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0           1  US-2023-103800 2023-01-03 2023-01-07  Standard Class
1           2  US-2023-112326 2023-01-04 2023-01-08  Standard Class
2           3  US-2023-112326 2023-01-04 2023-01-08  Standard Class
3           4  US-2023-112326 2023-01-04 2023-01-08  Standard Class
4           5  US-2023-141817 2023-01-05 2023-01-12  Standard Class
...       ...             ...        ...        ...             ...
10189   10190  US-2026-143259 2026-12-30 2027-01-03  Standard Class
10190   10191  US-2026-115427 2026-12-30 2027-01-03  Standard Class
10191   10192  US-2026-156720 2026-12-30 2027-01-03  Standard Class
10192   10193  US-2026-143259 2026-12-30 2027-01-03  Standard Class
10193   10194  CA-2026-143500 2026-12-30 2027-01-03  Standard Class

      Customer ID      Customer Name      Segment Country/Region  \
0        DP-13000      Darren Powers     Consumer  United States
1        PO-19195      Phillina Ober  Home Office  United States
2        PO-19195      Phillina Ober  Home Office  United States
3        PO-19195      Phillina Ober  Home Office  United States
4        MB-18085         Mick Brown     Consumer  United States
...           ...                ...          ...            ...
10189    PO-18865  Patrick O'Donnell     Consumer  United States
10190    EB-13975         Erica Bern    Corporate  United States
10191    JM-15580      Jill Matthias     Consumer  United States
10192    PO-18865  Patrick O'Donnell     Consumer  United States
10193    HO-15230        Harry Olson     Consumer         Canada

                City  ... Postal Code   Region       Product ID  \
0            Houston  ...       77095  Central  OFF-PA-10000174
1         Naperville  ...       60540  Central  OFF-BI-10004094
2         Naperville  ...       60540  Central  OFF-LA-10003223
3         Naperville  ...       60540  Central  OFF-ST-10002743
4       Philadelphia  ...       19143     East  OFF-AR-10003478
...              ...  ...         ...      ...              ...
10189  New York City  ...       10009     East  OFF-BI-10003684
10190      Fairfield  ...       94533     West  OFF-BI-10004632
10191       Loveland  ...       80538     West  OFF-FA-10003472
10192  New York City  ...       10009     East  TEC-PH-10004774
10193  Charlottetown  ...         C0A     East  OFF-BI-10004040

              Category Sub-Category  \
0      Office Supplies        Paper
1      Office Supplies      Binders
2      Office Supplies       Labels
3      Office Supplies      Storage
4      Office Supplies          Art
...                ...          ...
10189  Office Supplies      Binders
10190  Office Supplies      Binders
10191  Office Supplies    Fasteners
10192       Technology       Phones
10193  Office Supplies      Binders

                                            Product Name    Sales  Quantity  \
0      Message Book, Wirebound, Four 5 1/2" X 4" Form...   16.448         2
1             GBC Standard Plastic Binding Systems Combs    3.540         2
2                                              Avery 508   11.784         3
3                          SAFCO Boltless Steel Shelving  272.736         3
4      Avery Hi-Liter EverBold Pen Style Fluorescent ...   19.536         3
...                                                  ...      ...       ...
10189               Wilson Jones Legal Size Ring Binders   52.776         3
10190                                 GBC Binding covers   20.720         2
10191                                Bagged Rubber Bands    3.024         3
10192                          Gear Head AU3700S Headset   90.930         7
10193                        Wilson Jones Impact Binders    3.024         3

       Discount   Profit
0           0.2   5.5512
1           0.8  -5.4870
2           0.2   4.2717
3           0.2 -64.7748
4           0.2   4.8840
...         ...      ...
10189       0.2  19.7910
10190       0.2   6.4750
10191       0.2  -0.6048
10192       0.0   2.7279
10193       0.2  -0.6048

[10194 rows x 21 columns]>

## checking for null values

In [11]:
import numpy as np

In [12]:
Orders.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

## Checking for Duplicate records

In [13]:
Orders.duplicated().sum()

np.int64(0)

## checking for unique values

In [14]:
Orders.nunique()

Row ID            10194
Order ID           5111
Order Date         1242
Ship Date          1338
Ship Mode             4
Customer ID         804
Customer Name       800
Segment               3
Country/Region        2
City                542
State/Province       59
Postal Code         654
Region                4
Product ID         1862
Category              3
Sub-Category         17
Product Name       1849
Sales              6161
Quantity             14
Discount             12
Profit             7597
dtype: int64

In [15]:
Orders.dtypes

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
Country/Region            object
City                      object
State/Province            object
Postal Code               object
Region                    object
Product ID                object
Category                  object
Sub-Category              object
Product Name              object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
dtype: object

## Which product generated the highest total sales?

In [16]:
Orders.groupby("Product Name")["Sales"].sum().sort_values(ascending=False)

Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
                                                                                 ...
Avery Hi-Liter Pen Style Six-Color Fluorescent Set                                 7.700
Grip Seal Envelopes                                                                7.072
Xerox 20                                                                           6.480
Avery 5                                                                            5.760
Eureka Disposable Bags for Sanitaire Vibra Groomer I Upright Vac                   1.624
Name: Sales, Length: 1849, dtype: float64

## Which state generated the highest total profit?

In [17]:
Top_profit_states=Orders.groupby("State/Province")["Profit"].sum().sort_values(ascending=False)
Top_profit_states.head(5)

State/Province
California    76381.3871
New York      74038.5486
Washington    33402.6517
Michigan      24463.1876
Virginia      18597.9504
Name: Profit, dtype: float64

In [18]:
%config Completer.use_jedi = True

In [19]:
!pip show jedi

Name: jedi
Version: 0.20.0
Summary: An autocompletion tool for Python that can be used for text editors.
Home-page: https://github.com/davidhalter/jedi
Author: David Halter
Author-email: davidhalter88@gmail.com
License: MIT
Location: C:\Users\arshi\AppData\Roaming\Python\Python314\site-packages
Requires: parso
Required-by: ipython

In [20]:
import notebook
print(notebook.__version__)

7.4.3

In [22]:
%config Completer.use_jedi = True

In [ ]:
Orders.